name: LIDOM scrape (oficial)
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install requests beautifulsoup4 lxml
      - run: python scripts/scrape.py
      - name: Commit & push
        run: |
          git config user.name "vn-scraper"
          git config user.email "scraper@users.noreply.github.com"
          git add -A
          git commit -m "auto: refresh data" || echo "no changes"
          git push
