name: Actualizar juegos y posiciones LIDOM

on:
  schedule:
    - cron: "0 * * * *" # cada hora
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          pip install requests beautifulsoup4 lxml
          python scripts/scrape.py
      - name: Commit & push
        run: |
          git config user.name "vallebot"
          git config user.email "vallebot@users.noreply.github.com"
          git add .
          git commit -m "update automatico LIDOM" || echo "no changes"
          git push
